version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile #local django
    
    #django settings.py conifg 
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=djangodocker_db
      - DJANGO_DB_USERNAME=root
      - DJANGO_DB_PASSWORD=root
    ports:
      - "8000:8000"
    volumes:
      - ./:/code/
    command: bin/run.sh
    links:
      - db
    restart: always  
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=djangodocker_db
    restart: always
