version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile #local django
    
    #django settings.py conifg 
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=djangodocker_db
      - DJANGO_DB_USERNAME=root
      - DJANGO_DB_PASSWORD=root
    ports:
      - "8000:8000"
    volumes:
      - ./:/code/
    command: bash -c "python manage.py migrate && gunicorn hanium.wsgi -b 0.0.0.0:8000" #gunicorn hanium.wsgi:application --bind 0.0.0.0:8000 #bin/run.sh
    links:
      - db
    restart: always
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=djangodocker_db
    restart: always
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./compose/nginx:/etc/nginx/conf.d
    depends_on:
      - django
